datasets:
- name: ML-100K
  splitting:
    name: random
    params:
      seed: null
    test_ratio: 0.2
models:
  LensKit:
  - name: PopScore
    params:
      score_method: quantile
name: 1652358264_Untitled
rated_items_filter: true
top_K: 10
type: recommendation
