datasets:
- name: LFM-360K
  prefilters: []
  rating_modifier: null
  splitting:
    params: {}
    test_ratio: 0.2
    type: random
- name: LFM-1B
  prefilters: []
  rating_modifier: null
  splitting:
    params: {}
    test_ratio: 0.2
    type: random
evaluation:
- name: P@K
  params:
    K: 10
models:
  Implicit:
  - name: AlternatingLeastSquares
    params:
      calculate_training_loss: false
      factors: 100
      iterations: 15
      random_seed: null
      regularization: 0.01
      use_cg: true
      use_native: true
  LensKit:
  - name: PopScore
    params:
      score_method: quantile
name: 1649162862_HelloFRK
top_K: 10
type: recommendation
