# Perform E2E testing using Cypress library
name: End-to-End Testing

on:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install Python
        uses: actions/setup-python@v3
        
      - name: Install server dependencies
        working-directory: ./server
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install python-dotenv

      - name: Boot up server
        working-directory: ./server
        run: nohup flask run &
        
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
        env:
          working-directory: ./client
