name: Pytest with Coverage

on:
  workflow_dispatch:
  pull_request:
    branches:
      - stable
      - dev
  schedule:
    - cron: '0 22 * * 5'

jobs:
  test_coverage:
    name: Test coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install Python
        uses: actions/setup-python@v3
        
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install pytest
          pip install pytest-cov
          pip install pandas
          pip install PyYAML
          pip install Flask
          pip install Flask-Cors
          pip install requests
          pip install pillow
          pip install Cython
          pip install fairreckitlib
           
      - name: Run tests and coverage
        run: pytest ./server
