name: Server Pytest

on:
  workflow_dispatch:
  pull_request:
    branches: stable
  schedule:
    - cron: '0 22 * * 5'

jobs:
  test_coverage:
    name: Test coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install pytest
          pip install pandas
          pip install PyYAML
          pip install Flask
          pip install Flask-Cors
          pip install requests
          pip install pillow
          pip install Cython
          pip install fairreckitlib
      - name: Run pytest
        run: |
          pytest ./server
