name: Server Pytest

on:
  workflow_dispatch:
  pull_request:
    branches:
      - stable
      - dev
  schedule:
    - cron: '0 22 * * 5'

jobs:
  test_coverage:
    name: Test coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install Python
        uses: actions/setup-python@v3
        
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./server/requirements.txt
          pip install pytest-cov
           
      - name: Run tests and coverage
        run: |
          cd ./server
          pytest --cov
