name: Client Vitest

on:
  workflow_dispatch:
  pull_request:
    branches: [stable,dev]
  schedule:
    - cron: '0 22 * * 5'

jobs:
  run-vitest:
    name: Run Vitest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Run Vitest
        run: |
          cd ./client
          npm i
          npm run test